### PR TITLE
Move configs to text file

### PR DESCRIPTION
**Pull request by AliceFord**
Automatic merge disabled due to README update.

### CODE REVIEW

**Comment by ElectricityMachine** [comment]
Will be working on this for the next update.

**Comment by ElectricityMachine** [comment]
I apologize for not reviewing this sooner. 1 year is a very long time for something as simple as this, but the next release (looking like 0.4.0) is finally taking shape. As you can see, I changed the base branch for this PR to ``develop`` where I'm testing out a sizeable rewrite, along with updating the project to use Python 3.12.

Unfortunately, PyTorch doesn't have a build for 3.12 right now, and God only knows when that will become generally available and stable. Additionally, I'm not sure PyTorch would be appropriate for just a config handler, given that it's a neural network library. I'd like to propose an alternative method for configuration (either another PR to supersede or updating this one) that uses something more standardized, such as [ConfigParser](https://docs.python.org/3/library/configparser.html), which is built into Python. We can also consider [using a .json file](https://docs.python.org/3/library/json.html#module-json) too.

What are your thoughts on this?

**Comment by AliceFord** [comment]
> I apologize for not reviewing this sooner. 1 year is a very long time for something as simple as this, but the next release (looking like 0.4.0) is finally taking shape. As you can see, I changed the base branch for this PR to `develop` where I'm testing out a sizeable rewrite, along with updating the project to use Python 3.12.
> 
> Unfortunately, PyTorch doesn't have a build for 3.12 right now, and God only knows when that will become generally available and stable. Additionally, I'm not sure PyTorch would be appropriate for just a config handler, given that it's a neural network library. I'd like to propose an alternative method for configuration (either another PR to supersede or updating this one) that uses something more standardized, such as [ConfigParser](https://docs.python.org/3/library/configparser.html), which is built into Python. We can also consider [using a .json file](https://docs.python.org/3/library/json.html#module-json) too.
> 
> What are your thoughts on this?

Hi again, I won't lie I've completely forgotten about SCR! I was still not a great programmer back then (and perhaps neither am I now), but using something simpler seems much better (I'd lean towards json because it's compatible with almost everything).

**Comment by ElectricityMachine** [comment]
Agree about JSON, since it's easily human and machine readable. I will go ahead and close this in favor of {future PR} that uses JSON.

Given the increased reports of users having issues with master not supporting 3.12, {future PR} won't make it into 0.4, but will be at the top of the list for 0.5.

**Pull request closed without merging**
