### PR TITLE
SG+ 0.4: GUI Overhaul and Customizability

### PR DESCRIPTION
**Pull request by ameasere**
**Fixed**

- Camera button not working reliably
- Keypresses not committing fully to their assigned actions

**Added**

- GUI Overlay with live status
- Customizable settings and fine-tuning
- Automatic update window
- A standalone binary! No need for installing, source code mess and headaches
- Credits, because your hard work needs to be recognised

Binary link (it was too big to upload here): [Dropbox](https://www.dropbox.com/s/s3zgpytdwyk03gc/SGPlus-04.zip?dl=0)

The autoupdater will always appear unless the version on here is updated to 0.4, however this can be bypassed with simply making `"check_for_update"` in the `config.json` file set to `false` after first boot.

### CODE REVIEW

**Comment by cedriclenavet** [comment]
Seems nice, I can't wait to try it !

**Comment by enigmapr0ject** [comment]
I am aware in advance that in the binary, there are some issues with 0xC0..5 crashes and issues with loading. When a `config.json` file is made, set `"check_for_update"` to `false` and reload to fix the loading issues. The 0xC0..5 issues are to do with ACCESS VIOLATION problems, which are very unpredictable and hard to root out the cause. Will deep-dive this.

**Comment by ElectricityMachine** [comment]
Can you rebase onto ``master`` please? I just released 0.3.0 with some significant changes.

**Comment by enigmapr0ject** [comment]
Updated requirements, added checksum verification and signed the binary, while also removing some leftover bloat code. Also caught up the branch to match versions.

**Comment by ElectricityMachine** [comment]
I appreciate your contributions, but I will be closing this PR. Your work in this PR has not addressed my concerns in your previous PR #4, along with that I will list some additional issues:

1. The binary is signed and no build instructions are present. As this is an open source project, I do not feel comfortable with providing a signed binary not signed by me and without instructions on how to build it. I would go further and say that I don't feel comfortable providing a signed binary to begin with, as this is not reproducible. Also, the code signing certificate is in your real name and uses your real e-mail address, which is a larger security risk than someone tampering with a train game macro.
2. Said binary requires an internet connection to your API server to open and run. I glanced at the code and this is for checksum verification, but why does a Python script for a ROBLOX train game need this? I don't control this server, and I don't understand why a macro script needs to phone home.
3. This PR includes undocumented features, such as Discord Rich Presence support, and links to your own website.
4. While I couldn't run the executable myself, the UI as shown on your website still suffers from readability issues (peach background on white text)
5. There is still too much intertwining between the core code of the program that handles keystrokes and actions, and the GUI portion. This creates a project that isn't as maintainable as it should be, especially when I wouldn't even know how to maintain it if this was merged.

Overall, this PR doesn't align with my vision of a free and open source Python script for a small ROBLOX train game. It should be simple and easy to use, with the source code available for anyone to modify or audit. This PR adds significant complexity and as such I will be closing it.

**Comment by ameasere** [comment]
Closing a PR because a PR "doesn't align with my vision".

Yikes. Sounds like the Turbo disaster 2.0. If I remember correctly, you actually did approve and audit the source code when I sent it to you via DM months ago, but you quite literally abandoned the project. I am not even going to bother trying to address some of these ridiculous points, time is better spent elsewhere on projects where the entitled owner doesn't abandon the project but still try to ram his "vision" down contributors' throats.

**Comment by ImmortalAxolotl** [comment]
Bro, you have a fork, just use it.

**Comment by ElectricityMachine** [comment]
I'm sorry you feel that way. As @ImmortalAxolotl said, you're free to fork the project and use that as long as you abide by the license. I'll reiterate that this is a _simple_ Python macro for a ROBLOX train game, not some big software project with security requirements.
>Yikes. Sounds like the Turbo disaster 2.0.

kek
>you actually did approve and audit the source code when I sent it to you via DM months ago

Our last DM was in April of this year, and while you did send me the command to build the exe, I didn't "audit" or "approve" anything. Those instructions should've been included in this PR anyways.

>I am not even going to bother trying to address some of these ridiculous points

Ok. If you choose to in the future, I would be happy to discuss a solution that keeps bloat down while adding features that improve the user's experience, not a checksum phone-home or signed binary to protect against "tampering." for a GUI with white text on a light background.

>time is better spent elsewhere on projects where the entitled owner doesn't abandon the project but still try to ram his "vision" down contributors' throats.

kek

**Pull request closed without merging**
