### PR TITLE
Add enabled/disabled indicator at top of screen

### PR DESCRIPTION
**Pull request by cvbnxx**
very rudimentary message at the top of the screen i cobbled together. could probably be greatly improved but its a start

### CODE REVIEW

**Comment by ElectricityMachine** [comment]
This is a good start, thanks for contributing it! Could you enable maintainer edits on your repository? I'd like to make a few changes before merging if that's alright with you.

**Comment by cvbnxx** [comment]
the pr should have allow edits already enabled. if you can't edit then I'm not sure why.

**Comment by ElectricityMachine** [comment]
Yep, it does. Sorry for the confusion -- it was an error on my end. 

I made some modifications and I think it looks great. If you're happy with the way it turned out too, let me know and I'll merge.
RobloxPlayerBeta_9Ak8QoVUdc

**Comment by cvbnxx** [comment]
all good. your version looks a lot cleaner too.

**Pull request merged**
